//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.15 at 06:42:22 PM CEST 
//
/**
 * Example:
 <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<container>
    <rootfiles>
        <rootfile full-path="file:///dataFile1.xml" media-type="text/repetitormedia+xml"/>
        <rootfile full-path="file:///dataFile2.xml" media-type="text/repetitormedia+xml"/>
    </rootfiles>
</container>
 */

package de.free_creations.mediacontainer;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;


/**
 * <p>Java class for the XML Data contained in the file
 * "META-INF/container.xml". Please note that 
 * the JAXB wizard does not work nbm Modules.
 * see also:
 * http://netbeans.org/kb/docs/websvc/jaxb.html
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="rootfiles">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="rootfile" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                           &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rootfiles"
})
@XmlRootElement(name = "container")
public class ContainerInfoData {

    @XmlElement(required = true)
    protected ContainerInfoData.Rootfiles rootfiles;

    /**
     * Gets the value of the rootfiles property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerInfoData.Rootfiles }
     *     
     */
    public ContainerInfoData.Rootfiles getRootfiles() {
        return rootfiles;
    }

    /**
     * Sets the value of the rootfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerInfoData.Rootfiles }
     *     
     */
    public void setRootfiles(ContainerInfoData.Rootfiles value) {
        this.rootfiles = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="rootfile" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *                 &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rootfile"
    })
    public static class Rootfiles {

        @XmlElement(required = true)
        protected List<ContainerInfoData.Rootfiles.Rootfile> rootfile;

        /**
         * Gets the value of the rootfile property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rootfile property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRootfile().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ContainerInfoData.Rootfiles.Rootfile }
         * 
         * 
         */
        public List<ContainerInfoData.Rootfiles.Rootfile> getRootfile() {
            if (rootfile == null) {
                rootfile = new ArrayList<ContainerInfoData.Rootfiles.Rootfile>();
            }
            return this.rootfile;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="full-path" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *       &lt;attribute name="media-type" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Rootfile {

            @XmlAttribute(name = "full-path")
            @XmlSchemaType(name = "anyURI")
            protected String fullPath;
            @XmlAttribute(name = "media-type")
            @XmlSchemaType(name = "anyURI")
            protected String mediaType;

            /**
             * Gets the value of the fullPath property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullPath() {
                return fullPath;
            }

            /**
             * Sets the value of the fullPath property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullPath(String value) {
                this.fullPath = value;
            }

            /**
             * Gets the value of the mediaType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMediaType() {
                return mediaType;
            }

            /**
             * Sets the value of the mediaType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMediaType(String value) {
                this.mediaType = value;
            }

        }

    }

}
